import React from 'react'
import {
  IconSkillNginx,
  IconSkillCSS,
  IconSkillDocker,
  IconSkillFigmaDark,
  IconSkillFigmaLight,
  IconSkillHTML,
  IconSkillJavaScript,
  IconSkillMysqlDark,
  IconSkillMysqlLight,
  IconSkillNextjsDark,
  IconSkillNextjsLight,
  IconSkillNodejsDark,
  IconSkillNodejsLight,
  IconSkillPrisma,
  IconSkillReactDark,
  IconSkillReactLight,
  IconSkillTailwindcssDark,
  IconSkillTailwindcssLight,
  IconSkillTypeScript,
  IconSkillDotnet,
  IconSkillViteDark,
  IconSkillViteLight,
  IconSkillVuejsDark,
  IconSkillVuejsLight,
  IconSkillVuetifyDark,
  IconSkillVuetifyLight,
  IconSkillAzureDark,
  IconSkillAzureLight,
  IconSkillCloudflareDark,
  IconSkillCloudflareLight,
  IconSkillCypressDark,
  IconSkillCypressLight,
  IconSkillExpressjsDark,
  IconSkillExpressjsLight,
  IconSkillIpfsDark,
  IconSkillIpfsLight,
  IconSkillLessDark,
  IconSkillLessLight,
  IconSkillNeovimDark,
  IconSkillNeovimLight,
  IconSkillNotionDark,
  IconSkillNotionLight,
  IconSkillObsidianDark,
  IconSkillObsidianLight,
  IconSkillVercelDark,
  IconSkillVercelLight,
  IconSkillWebpackDark,
  IconSkillWebpackLight,
  IconSkillDjango,
  IconSkillSolidity,
  IconSkillEmotionLight,
  IconSkillEmotionDark,
  IconSkillWebassembly,
  IconSkillVscodeDark,
  IconSkillVscodeLight,
  IconSkillCpp,
  IconSkillJest,
  IconSkillPythonLight,
  IconSkillPythonDark,
  IconSkillRollupjsDark,
  IconSkillRollupjsLight,
  IconSkillSentry,
  IconSkillSvelte,
  IconSkillGraphqlDark,
  IconSkillGraphqlLight,
  IconSkillHardhat,
} from '@/components/icons'

export const frontendSkills = [
  { icon: <IconSkillReactDark />, darkIcon: <IconSkillReactLight />, name: 'React' },
  { icon: <IconSkillVuejsDark />, darkIcon: <IconSkillVuejsLight />, name: 'Vue.js' },
  { icon: <IconSkillSvelte />, name: 'Svelte' },
  { icon: <IconSkillNextjsDark />, darkIcon: <IconSkillNextjsLight />, name: 'Next.js' },
  {
    icon: <IconSkillTailwindcssDark />,
    darkIcon: <IconSkillTailwindcssLight />,
    name: 'Tailwind CSS',
  },
  { icon: <IconSkillLessDark />, darkIcon: <IconSkillLessLight />, name: 'Less' },
  { icon: <IconSkillEmotionDark />, darkIcon: <IconSkillEmotionLight />, name: 'Emotion' },
  { icon: <IconSkillWebpackDark />, darkIcon: <IconSkillWebpackLight />, name: 'Webpack' },
  { icon: <IconSkillViteDark />, darkIcon: <IconSkillViteLight />, name: 'Vite' },
  { icon: <IconSkillRollupjsDark />, darkIcon: <IconSkillRollupjsLight />, name: 'Rollup.js' },
]

export const languageSkills = [
  { icon: <IconSkillCSS />, name: 'CSS' },
  { icon: <IconSkillHTML />, name: 'HTML' },
  { icon: <IconSkillJavaScript />, name: 'JavaScript' },
  { icon: <IconSkillTypeScript />, name: 'TypeScript' },
  { icon: <IconSkillPythonDark />, darkIcon: <IconSkillPythonLight />, name: 'Python' },
  { icon: <IconSkillCpp />, name: 'C++' },
  { icon: <IconSkillSolidity />, name: 'Solidity' },
]

export const otherSkills = [
  { icon: <IconSkillNginx />, name: 'Nginx' },
  { icon: <IconSkillDocker />, name: 'Docker' },
  { icon: <IconSkillMysqlDark />, darkIcon: <IconSkillMysqlLight />, name: 'MySQL' },
  { icon: <IconSkillNodejsDark />, darkIcon: <IconSkillNodejsLight />, name: 'Node.js' },
  { icon: <IconSkillPrisma />, name: 'Prisma' },
  { icon: <IconSkillDotnet />, name: '.NET' },
  { icon: <IconSkillVuetifyDark />, darkIcon: <IconSkillVuetifyLight />, name: 'Vuetify' },
  { icon: <IconSkillAzureDark />, darkIcon: <IconSkillAzureLight />, name: 'Azure' },
  { icon: <IconSkillCloudflareDark />, darkIcon: <IconSkillCloudflareLight />, name: 'Cloudflare' },
  { icon: <IconSkillCypressDark />, darkIcon: <IconSkillCypressLight />, name: 'Cypress' },
  { icon: <IconSkillExpressjsDark />, darkIcon: <IconSkillExpressjsLight />, name: 'Express.js' },
  { icon: <IconSkillIpfsDark />, darkIcon: <IconSkillIpfsLight />, name: 'IPFS' },
  { icon: <IconSkillNeovimDark />, darkIcon: <IconSkillNeovimLight />, name: 'Neovim' },
  { icon: <IconSkillNotionDark />, darkIcon: <IconSkillNotionLight />, name: 'Notion' },
  { icon: <IconSkillObsidianDark />, darkIcon: <IconSkillObsidianLight />, name: 'Obsidian' },
  { icon: <IconSkillVercelDark />, darkIcon: <IconSkillVercelLight />, name: 'Vercel' },
  { icon: <IconSkillDjango />, name: 'Django' },
  { icon: <IconSkillWebassembly />, name: 'WebAssembly' },
  { icon: <IconSkillVscodeDark />, darkIcon: <IconSkillVscodeLight />, name: 'VS Code' },
  { icon: <IconSkillJest />, name: 'Jest' },
  { icon: <IconSkillSentry />, name: 'Sentry' },
  { icon: <IconSkillGraphqlDark />, darkIcon: <IconSkillGraphqlLight />, name: 'GraphQL' },
  { icon: <IconSkillHardhat />, name: 'Hardhat' },
]

export const allSkills = [...frontendSkills, ...languageSkills, ...otherSkills]

export default allSkills
